apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: ticket-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: aravindroy1/ticket-generator:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:postgrespassword@postgres:5432/ticket_db"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
