version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - payment-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - payment-network

  payment-service:
    build: .
    container_name: payment-service
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@mysql:3306/payment_service"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - payment-network

volumes:
  mysql_data:

networks:
  payment-network:
    driver: bridge