apiVersion: v1
kind: ConfigMap
metadata:
  name: team3-config
data:
  # Database Hosts & Configurations
  DB_HOST: "mysql-service"
  MYSQL_HOST: "mysql-service"
  MYSQL_USER: "root"
  DB_USER: "root"
  DB_NAME: "team3_db"
  MYSQL_DB: "team3_db"
  MYSQL_DATABASE: "team3_db"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "team3_pg_db"
  DATABASE_URL_EVENT: "postgresql://postgres:postgrespassword@postgres-service:5432/team3_pg_db"
  DATABASE_URL_PAYMENT: "mysql+pymysql://root:root@mysql-service:3306/team3_db"
  DATABASE_URL_TICKET: "postgresql+asyncpg://postgres:postgrespassword@postgres-service:5432/team3_pg_db"
  DATABASE_URL_NOTIF: "postgresql://postgres:postgrespassword@postgres-service:5432/team3_pg_db"

  # Message Broker Configurations
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672/"
  RABBITMQ_QUEUE: "notifications"

  # API Endpoints
  EVENT_SERVICE_URL: "http://event-service:8000/api/v1/events"
  PAYMENT_SERVICE_URL: "http://payment-service:8000/payments"

  # Notification Service settings
  EMAIL_USER: "team3@example.com"
