apiVersion: v1
kind: Secret
metadata:
  name: team3-secrets
type: Opaque
data:
  # Base64 encoded secrets
  # root
  MYSQL_ROOT_PASSWORD: cm9vdA==
  # root
  DB_PASSWORD: cm9vdA==
  # postgrespassword
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==
  # guest
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  # password
  EMAIL_PASSWORD: cGFzc3dvcmQ=
  # team3_super_secret_jwt_key_2026
  JWT_SECRET: dGVhbTNfc3VwZXJfc2VjcmV0X2p3dF9rZXlfMjAyNg==
  # root
  MYSQL_PASSWORD: cm9vdA==
  # team3_super_secret_jwt_key_2026
  SECRET_KEY: dGVhbTNfc3VwZXJfc2VjcmV0X2p3dF9rZXlfMjAyNg==
